apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  labels:
    env: demo
spec:
  type: ClusterIP # or remove this because default is cluster ip
  ports:
  - port: 80
    targetPort: 80
  selector:
    env: demo